# Generated by Django 5.2.4 on 2025-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
