# Generated by Django 5.2.4 on 2025-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user_qr/'),
        ),
        migrations.AddField(
            model_name='account',
            name='seller_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('banned', 'Banned'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
